# Header
menu:
  Vida: /vida
  Obras: /obras
  Quienes Somos: /about
  Casa de Ejercicios: /casa
  Cartas: /cartas
  Prensa: /prensa
  Contacto: /contacto

# Logo Image Source
logo_src: /images/logo.svg

# Theme Main Subtitle
subtitle_main: Subtitulo principal

# Theme Secondary subtitle
susbtitle_secondary: Subtitulo secundario

# Footer About Section
about_footer: Esto es el footer.

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://media.argibay.org/Mama_Antula_416x450.png"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  # disqus_shortname: klugjo
  # Facebook comments
  facebook:
    appid: 1234
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/?lang=es
facebook_url: https://www.facebook.com/
instagram_url: https://www.instagram.com/
dribble_url: https://dribbble.com/
github_url: https://github.com/klugjo/hexo-theme-phantom/commits?author=klugjo
googleplus_url: https://plus.google.com/
behance_url: https://www.behance.net/
fivehundredpx_url: https://500px.com/
email_url: \#
rss_url: \#
